# insert into public.data (value, departament_id, direction_id, month, year) values (0, 6, 8, 12, 2024);
# insert into public.data (value, departament_id, direction_id, month, year) values (0, 7, 8, 12, 2024);
# insert into public.data (value, departament_id, direction_id, month, year) values (0, 8, 8, 12, 2024);
# insert into public.data (value, departament_id, direction_id, month, year) values (0, 9, 8, 12, 2024);
# insert into public.data (value, departament_id, direction_id, month, year) values (0, 10, 8, 12, 2024);
# insert into public.data (value, departament_id, direction_id, month, year) values (0, 11, 8, 12, 2024);
# insert into public.data (value, departament_id, direction_id, month, year) values (0, 12, 8, 12, 2024);
# insert into public.data (value, departament_id, direction_id, month, year) values (0, 13, 8, 12, 2024);
# insert into public.data (value, departament_id, direction_id, month, year) values (0, 14, 8, 12, 2024);
# insert into public.data (value, departament_id, direction_id, month, year) values (0, 15, 8, 12, 2024);

# insert into direction (direction) values ('Общая смертность');
# insert into departament (departament) values ('Онкология');
# insert into departament (departament) values ('БСК');
# insert into departament (departament) values ('ИМ первичный');
# insert into departament (departament) values ('ИМ повторный');
# insert into departament (departament) values ('ОНМК первичное');
# insert into departament (departament) values ('ОНМК повторное');
# insert into departament (departament) values ('Другое');
# insert into direction (direction) values ('Tbc');
# insert into departament (departament) values ('Tbc');
# insert into direction (direction) values ('ВИЧ');
# insert into departament (departament) values ('ВИЧ');
# insert into direction (direction) values ('Количество пациентов, осмотренных в рамках ДН');
# insert into departament (departament) values ('СД');
# insert into direction (direction) values ('Проведен контроль ЦП, из них достигнуты целевые значения');
# insert into departament (departament) values ('HbA1c, %');
# insert into departament (departament) values ('ЛПНП');
# insert into direction (direction) values ('Средняя доза статинов на сутки');
# insert into departament (departament) values ('Средняя доза статинов на сутки');
# insert into direction (direction) values ('Направлены на ВТМП (БСК)');
# insert into departament (departament) values ('Направлены на ВТМП (БСК)');
# insert into direction (direction) values ('Количество проведенных ВТМП планово');
# insert into direction (direction) values ('Наличие вакцинации в соответствии с национальным календарем прививок (Дифтерия, гепатит В, пневмококковая инфекция)');
# insert into departament (departament) values ('Наличие вакцинации в соответствии с национальным календарем прививок (Дифтерия, гепатит В, пневмококковая инфекция)');
# insert into direction (direction) values ('Вызывали скорую  помощь 2 и более раз (ХНИЗ)');
# insert into departament (departament) values ('БА, ХОБЛ');
# insert into direction (direction) values ('Количество ОССЗ');
# insert into departament (departament) values ('первичных');
# insert into departament (departament) values ('повторных');
# insert into direction (direction) values ('Количество экстренных госпитализаций');
# insert into direction (direction) values ('Пропуск социальнозначимых заболеваний (запущенные формы), состоящих на диспансерном наблюдении');
# insert into direction (direction) values ('Онкология всего');
# insert into departament (departament) values ('1-2 стадия');
# insert into departament (departament) values ('Впервые выявленные - запущенные');


insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 18, 9, 1, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 18, 9, 2, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 18, 9, 3, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 18, 9, 4, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 18, 9, 5, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 18, 9, 6, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 18, 9, 7, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 18, 9, 8, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 18, 9, 9, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 18, 9, 10, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 18, 9, 11, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 18, 9, 12, 2024, 2);

insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 19, 9, 1, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 19, 9, 2, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 19, 9, 3, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 19, 9, 4, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 19, 9, 5, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 19, 9, 6, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 19, 9, 7, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 19, 9, 8, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 19, 9, 9, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 19, 9, 10, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 19, 9, 11, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 19, 9, 12, 2024, 2);

insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 20, 9, 1, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 20, 9, 2, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 20, 9, 3, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 20, 9, 4, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 20, 9, 5, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 20, 9, 6, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 20, 9, 7, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 20, 9, 8, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 20, 9, 9, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 20, 9, 10, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 20, 9, 11, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 20, 9, 12, 2024, 2);

insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 21, 9, 1, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 21, 9, 2, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 21, 9, 3, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 21, 9, 4, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 21, 9, 5, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 21, 9, 6, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 21, 9, 7, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 21, 9, 8, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 21, 9, 9, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 21, 9, 10, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 21, 9, 11, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 21, 9, 12, 2024, 2);

insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 22, 9, 1, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 22, 9, 2, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 22, 9, 3, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 22, 9, 4, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 22, 9, 5, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 22, 9, 6, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 22, 9, 7, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 22, 9, 8, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 22, 9, 9, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 22, 9, 10, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 22, 9, 11, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 22, 9, 12, 2024, 2);

insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 23, 9, 1, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 23, 9, 2, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 23, 9, 3, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 23, 9, 4, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 23, 9, 5, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 23, 9, 6, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 23, 9, 7, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 23, 9, 8, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 23, 9, 9, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 23, 9, 10, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 23, 9, 11, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 23, 9, 12, 2024, 2);

insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 24, 9, 1, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 24, 9, 2, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 24, 9, 3, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 24, 9, 4, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 24, 9, 5, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 24, 9, 6, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 24, 9, 7, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 24, 9, 8, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 24, 9, 9, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 24, 9, 10, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 24, 9, 11, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 24, 9, 12, 2024, 2);

insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 25, 10, 1, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 25, 10, 2, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 25, 10, 3, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 25, 10, 4, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 25, 10, 5, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 25, 10, 6, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 25, 10, 7, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 25, 10, 8, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 25, 10, 9, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 25, 10, 10, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 25, 10, 11, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 25, 10, 12, 2024, 2);

insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 26, 11, 1, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 26, 11, 2, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 26, 11, 3, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 26, 11, 4, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 26, 11, 5, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 26, 11, 6, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 26, 11, 7, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 26, 11, 8, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 26, 11, 9, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 26, 11, 10, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 26, 11, 11, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 26, 11, 12, 2024, 2);

insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 19, 12, 1, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 19, 12, 2, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 19, 12, 3, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 19, 12, 4, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 19, 12, 5, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 19, 12, 6, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 19, 12, 7, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 19, 12, 8, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 19, 12, 9, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 19, 12, 10, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 19, 12, 11, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 19, 12, 12, 2024, 2);

insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 27, 12, 1, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 27, 12, 2, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 27, 12, 3, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 27, 12, 4, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 27, 12, 5, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 27, 12, 6, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 27, 12, 7, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 27, 12, 8, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 27, 12, 9, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 27, 12, 10, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 27, 12, 11, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 27, 12, 12, 2024, 2);

insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 24, 12, 1, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 24, 12, 2, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 24, 12, 3, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 24, 12, 4, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 24, 12, 5, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 24, 12, 6, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 24, 12, 7, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 24, 12, 8, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 24, 12, 9, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 24, 12, 10, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 24, 12, 11, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 24, 12, 12, 2024, 2);

insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 28, 13, 1, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 28, 13, 2, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 28, 13, 3, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 28, 13, 4, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 28, 13, 5, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 28, 13, 6, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 28, 13, 7, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 28, 13, 8, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 28, 13, 9, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 28, 13, 10, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 28, 13, 11, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 28, 13, 12, 2024, 2);

insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 29, 13, 1, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 29, 13, 2, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 29, 13, 3, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 29, 13, 4, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 29, 13, 5, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 29, 13, 6, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 29, 13, 7, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 29, 13, 8, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 29, 13, 9, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 29, 13, 10, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 29, 13, 11, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 29, 13, 12, 2024, 2);

insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 30, 14, 1, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 30, 14, 2, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 30, 14, 3, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 30, 14, 4, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 30, 14, 5, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 30, 14, 6, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 30, 14, 7, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 30, 14, 8, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 30, 14, 9, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 30, 14, 10, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 30, 14, 11, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 30, 14, 12, 2024, 2);

insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 31, 15, 1, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 31, 15, 2, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 31, 15, 3, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 31, 15, 4, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 31, 15, 5, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 31, 15, 6, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 31, 15, 7, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 31, 15, 8, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 31, 15, 9, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 31, 15, 10, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 31, 15, 11, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 31, 15, 12, 2024, 2);

insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 19, 16, 1, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 19, 16, 2, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 19, 16, 3, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 19, 16, 4, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 19, 16, 5, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 19, 16, 6, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 19, 16, 7, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 19, 16, 8, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 19, 16, 9, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 19, 16, 10, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 19, 16, 11, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 19, 16, 12, 2024, 2);

insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 24, 16, 1, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 24, 16, 2, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 24, 16, 3, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 24, 16, 4, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 24, 16, 5, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 24, 16, 6, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 24, 16, 7, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 24, 16, 8, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 24, 16, 9, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 24, 16, 10, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 24, 16, 11, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 24, 16, 12, 2024, 2);

insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 32, 17, 1, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 32, 17, 2, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 32, 17, 3, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 32, 17, 4, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 32, 17, 5, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 32, 17, 6, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 32, 17, 7, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 32, 17, 8, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 32, 17, 9, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 32, 17, 10, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 32, 17, 11, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 32, 17, 12, 2024, 2);

insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 19, 18, 1, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 19, 18, 2, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 19, 18, 3, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 19, 18, 4, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 19, 18, 5, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 19, 18, 6, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 19, 18, 7, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 19, 18, 8, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 19, 18, 9, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 19, 18, 10, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 19, 18, 11, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 19, 18, 12, 2024, 2);

insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 33, 18, 1, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 33, 18, 2, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 33, 18, 3, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 33, 18, 4, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 33, 18, 5, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 33, 18, 6, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 33, 18, 7, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 33, 18, 8, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 33, 18, 9, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 33, 18, 10, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 33, 18, 11, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 33, 18, 12, 2024, 2);

insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 27, 18, 1, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 27, 18, 2, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 27, 18, 3, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 27, 18, 4, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 27, 18, 5, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 27, 18, 6, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 27, 18, 7, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 27, 18, 8, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 27, 18, 9, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 27, 18, 10, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 27, 18, 11, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 27, 18, 12, 2024, 2);

insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 24, 18, 1, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 24, 18, 2, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 24, 18, 3, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 24, 18, 4, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 24, 18, 5, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 24, 18, 6, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 24, 18, 7, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 24, 18, 8, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 24, 18, 9, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 24, 18, 10, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 24, 18, 11, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 24, 18, 12, 2024, 2);

insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 19, 23, 1, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 19, 23, 2, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 19, 23, 3, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 19, 23, 4, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 19, 23, 5, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 19, 23, 6, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 19, 23, 7, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 19, 23, 8, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 19, 23, 9, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 19, 23, 10, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 19, 23, 11, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 19, 23, 12, 2024, 2);

insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 33, 23, 1, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 33, 23, 2, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 33, 23, 3, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 33, 23, 4, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 33, 23, 5, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 33, 23, 6, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 33, 23, 7, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 33, 23, 8, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 33, 23, 9, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 33, 23, 10, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 33, 23, 11, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 33, 23, 12, 2024, 2);

insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 27, 23, 1, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 27, 23, 2, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 27, 23, 3, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 27, 23, 4, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 27, 23, 5, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 27, 23, 6, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 27, 23, 7, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 27, 23, 8, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 27, 23, 9, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 27, 23, 10, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 27, 23, 11, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 27, 23, 12, 2024, 2);

insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 24, 23, 1, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 24, 23, 2, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 24, 23, 3, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 24, 23, 4, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 24, 23, 5, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 24, 23, 6, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 24, 23, 7, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 24, 23, 8, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 24, 23, 9, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 24, 23, 10, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 24, 23, 11, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 24, 23, 12, 2024, 2);


insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 34, 19, 1, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 34, 19, 2, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 34, 19, 3, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 34, 19, 4, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 34, 19, 5, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 34, 19, 6, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 34, 19, 7, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 34, 19, 8, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 34, 19, 9, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 34, 19, 10, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 34, 19, 11, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 34, 19, 12, 2024, 2);

insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 35, 19, 1, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 35, 19, 2, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 35, 19, 3, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 35, 19, 4, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 35, 19, 5, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 35, 19, 6, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 35, 19, 7, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 35, 19, 8, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 35, 19, 9, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 35, 19, 10, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 35, 19, 11, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 35, 19, 12, 2024, 2);

insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 19, 20, 1, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 19, 20, 2, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 19, 20, 3, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 19, 20, 4, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 19, 20, 5, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 19, 20, 6, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 19, 20, 7, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 19, 20, 8, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 19, 20, 9, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 19, 20, 10, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 19, 20, 11, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 19, 20, 12, 2024, 2);

insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 33, 20, 1, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 33, 20, 2, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 33, 20, 3, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 33, 20, 4, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 33, 20, 5, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 33, 20, 6, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 33, 20, 7, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 33, 20, 8, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 33, 20, 9, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 33, 20, 10, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 33, 20, 11, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 33, 20, 12, 2024, 2);

insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 27, 20, 1, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 27, 20, 2, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 27, 20, 3, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 27, 20, 4, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 27, 20, 5, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 27, 20, 6, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 27, 20, 7, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 27, 20, 8, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 27, 20, 9, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 27, 20, 10, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 27, 20, 11, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 27, 20, 12, 2024, 2);

insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 24, 20, 1, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 24, 20, 2, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 24, 20, 3, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 24, 20, 4, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 24, 20, 5, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 24, 20, 6, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 24, 20, 7, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 24, 20, 8, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 24, 20, 9, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 24, 20, 10, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 24, 20, 11, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 24, 20, 12, 2024, 2);

insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 25, 21, 1, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 25, 21, 2, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 25, 21, 3, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 25, 21, 4, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 25, 21, 5, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 25, 21, 6, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 25, 21, 7, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 25, 21, 8, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 25, 21, 9, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 25, 21, 10, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 25, 21, 11, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 25, 21, 12, 2024, 2);

insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 26, 21, 1, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 26, 21, 2, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 26, 21, 3, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 26, 21, 4, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 26, 21, 5, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 26, 21, 6, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 26, 21, 7, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 26, 21, 8, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 26, 21, 9, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 26, 21, 10, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 26, 21, 11, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 26, 21, 12, 2024, 2);

insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 18, 21, 1, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 18, 21, 2, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 18, 21, 3, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 18, 21, 4, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 18, 21, 5, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 18, 21, 6, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 18, 21, 7, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 18, 21, 8, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 18, 21, 9, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 18, 21, 10, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 18, 21, 11, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 18, 21, 12, 2024, 2);

insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 36, 22, 1, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 36, 22, 2, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 36, 22, 3, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 36, 22, 4, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 36, 22, 5, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 36, 22, 6, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 36, 22, 7, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 36, 22, 8, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 36, 22, 9, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 36, 22, 10, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 36, 22, 11, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 36, 22, 12, 2024, 2);

insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 37, 22, 1, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 37, 22, 2, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 37, 22, 3, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 37, 22, 4, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 37, 22, 5, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 37, 22, 6, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 37, 22, 7, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 37, 22, 8, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 37, 22, 9, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 37, 22, 10, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 37, 22, 11, 2024, 2);
insert into public.data (value, departament_id, direction_id, month, year, table_id) values (0, 37, 22, 12, 2024, 2);